# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12XzAoE6MbySOLdc19lIO_gaoVnUVjCC7
"""

# 📦 Import libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.datasets import make_regression

# 🧪 Generate dummy regression data
X, y = make_regression(n_samples=100, n_features=1, noise=20, random_state=42)

# ⚙️ Create and train the model
model = LinearRegression()
model.fit(X, y)

# 📈 Predict values
y_pred = model.predict(X)

# 🎨 Plot results
plt.figure(figsize=(8,5))
plt.scatter(X, y, color='blue', label='Actual Data')
plt.plot(X, y_pred, color='red', label='Prediction Line')
plt.title("Linear Regression Example")
plt.xlabel("Input Feature (X)")
plt.ylabel("Target Output (y)")
plt.legend()
plt.grid(True)
plt.show()

